name: Backend CI

on:
  push:
    branches:
      - "**"
    paths:
      - "backend/**"
  pull_request:
    branches:
      - "**"
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  changeset:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
        id: checkout
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'

  ci:
    name: Run Linting and Tests
    needs: [changeset]
    if: ${{ needs.changeset.outputs.backend == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ["8.2"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        id: checkout

      - name: Set Up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        id: setup-php
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, ctype, iconv
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: pcov

      - name: Cache Composer Dependencies
        uses: actions/cache@v4
        id: composer-cache
        with:
          path: backend/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('backend/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        id: install-deps
        working-directory: backend
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run Linting
        id: linting
        working-directory: backend
        run: composer lint

      - name: Run Unit Tests
        id: unit-tests
        working-directory: backend
        run: composer test